# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-05 13:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('card_number', models.CharField(max_length=16)),
                ('message', models.TextField()),
            ],
        ),
    ]
