# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 04:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='name',
        ),
        migrations.AddField(
            model_name='donation',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
