# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 15:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_auto_20170407_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
