# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-08 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0004_auto_20170408_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='donation_made',
            field=models.DateTimeField(null=True),
        ),
    ]
