# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-04-09 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0005_donation_donation_made'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='cvv',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
